# Generated by Django 4.2.3 on 2023-10-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_checkout_checkoutprodcut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutProdcut',
            new_name='CheckoutProduct',
        ),
    ]
